version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/restapi-demo

permissions:
  - object: /home/ec2-user/restapi-demo
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: ec2-user || true     